export const Colors = {
  primary: "#F4531F",
  primaryLight: "#FF8A50",
  primaryDark: "#D6430F",
  background: "#FFFFFF",
  surface: "#F6F7F9",
  surfaceBorder: "#E7EAF0",
  cardBorder: "#E1E4EA",
  text: {
    primary: "#1C2B46",
    secondary: "#6C7A93",
    muted: "#9AA6BC",
    light: "#B4BDCC",
    inverse: "#FFFFFF",
  },
  input: {
    background: "#F6F7F9",
    border: "#E7EAF0",
  },
  success: "#0C9D61",
  successLight: "#E7F7EF",
  successDark: "#0A7C4E",
  warning: "#E9A23B",
  warningLight: "#FDF3E3",
  warningDark: "#B97B17",
  error: "#E23D3D",
  errorLight: "#FDEBEB",
  tint: "#FEEFE8",
  navBar: "#F6F7F9",
  transparent: "transparent",
} as const;
