/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated organization's profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Organization profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Organization"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the authenticated organization's profile */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Updated organization profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Organization"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        trace?: never;
    };
    "/organization/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export a data-portability snapshot of the organization's own data
         * @description FR-132/GDPR data portability. A real, if not GDPR-complete, snapshot of what this org's own data looks like today (profile, roles, memberships) — grows as more tenant-scoped models are added. A separate, more sensitive scope than core.organization.read.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Organization data export */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrganizationExport"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the organization's members */
        get: {
            parameters: {
                query?: {
                    /** @description Page size, clamped to [1, 100]; invalid/absent falls back to the default. */
                    limit?: components["parameters"]["PageLimit"];
                    /** @description Opaque cursor from a previous page's `nextCursor` — omit for the first page. */
                    cursor?: components["parameters"]["PageCursor"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cursor-paginated member list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            members: components["schemas"]["Member"][];
                            nextCursor: string | null;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** Invite a new member by email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        /** @description Pre-assign a Role by id, applied when the invite is accepted. */
                        roleId?: string;
                    };
                };
            };
            responses: {
                /** @description Invite created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            inviteId: string;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description OrganizationMembership id */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member (frees the seat they held) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description OrganizationMembership id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Member removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the organization's pending (unaccepted, unexpired) invites */
        get: {
            parameters: {
                query?: {
                    /** @description Page size, clamped to [1, 100]; invalid/absent falls back to the default. */
                    limit?: components["parameters"]["PageLimit"];
                    /** @description Opaque cursor from a previous page's `nextCursor` — omit for the first page. */
                    cursor?: components["parameters"]["PageCursor"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cursor-paginated pending-invite list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            invites: components["schemas"]["Invite"][];
                            nextCursor: string | null;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/invites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description OrganizationInvite id */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel a pending invite */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description OrganizationInvite id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invite cancelled */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the organization's custom roles */
        get: {
            parameters: {
                query?: {
                    /** @description Page size, clamped to [1, 100]; invalid/absent falls back to the default. */
                    limit?: components["parameters"]["PageLimit"];
                    /** @description Opaque cursor from a previous page's `nextCursor` — omit for the first page. */
                    cursor?: components["parameters"]["PageCursor"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cursor-paginated role list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            roles: components["schemas"]["Role"][];
                            nextCursor: string | null;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** Create a custom role */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Role created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Role"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Role id */
                id: string;
            };
            cookie?: never;
        };
        /** Get a role, including its granted permission keys */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Role id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Role detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoleDetail"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete a role */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Role id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Role deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Replace a role's entire permission set */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Role id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Permission catalog keys (e.g. "core.roles.manage"), not raw ids. Replaces the role's full set — omitted keys are removed. */
                        permissionKeys: string[];
                    };
                };
            };
            responses: {
                /** @description Updated role detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoleDetail"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/roles/{id}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Role id */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant a role to a member (idempotent) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Role id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Must be an ACTIVE member of this organization. */
                        userId: string;
                    };
                };
            };
            responses: {
                /** @description Grant created (or already existed) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description No role with that id (including one belonging to another organization) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}/assignments/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Role id */
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a role from a member */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Role id */
                    id: string;
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Grant removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description That role is not assigned to that user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the organization's own settings (sensitive values redacted) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Setting list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            settings: components["schemas"]["Setting"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        /** Get one setting by key (sensitive values redacted, same as the list endpoint) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Setting */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Setting"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        /** Create or update a setting (upsert) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        category: string;
                        value: unknown;
                        /** @description Encrypted at rest if true; redacted on every subsequent read, including by the caller that set it. */
                        isSensitive?: boolean;
                    };
                };
            };
            responses: {
                /** @description Echoes what was just submitted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Setting"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the organization's API keys (never the hash, never the raw key) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API key list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            apiKeys: components["schemas"]["ApiKey"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /**
         * Create a new API key
         * @description Self-escalation guard: the requested `scopes` must be a subset of the calling key's own scopes, or this 403s without creating anything.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        /** @description Permission catalog keys; must be a subset of the calling key's own scopes. */
                        scopes: string[];
                        /** Format: date-time */
                        expiresAt?: string;
                    };
                };
            };
            responses: {
                /** @description Created key, including the raw key exactly once */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiKeyCreated"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description Key is missing the core.api_keys.manage scope, or requested scopes exceed the caller's own (self-escalation guard) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API key */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Key revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List publicly visible plans (global catalog, not org-owned) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plan list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            plans: components["schemas"]["Plan"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the organization's active subscription, if any */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active subscription, or null if none */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            subscription: components["schemas"]["Subscription"] | null;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the organization's invoices */
        get: {
            parameters: {
                query?: {
                    /** @description Page size, clamped to [1, 100]; invalid/absent falls back to the default. */
                    limit?: components["parameters"]["PageLimit"];
                    /** @description Opaque cursor from a previous page's `nextCursor` — omit for the first page. */
                    cursor?: components["parameters"]["PageCursor"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cursor-paginated invoice list (summary fields, no line items) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            invoices: components["schemas"]["InvoiceSummary"][];
                            nextCursor: string | null;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/invoices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invoice id */
                id: string;
            };
            cookie?: never;
        };
        /** Get an invoice with its line items */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Invoice id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invoice detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InvoiceDetail"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current usage/limit for every registered resource type
         * @description One request instead of one per resource type — each entry's `limit` is resolved from the organization's active subscription's plan (null = unlimited: no active subscription, or the plan doesn't allocate that resource type).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resource usage summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            usage: components["schemas"]["ResourceUsageEntry"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sessions currently active within the organization
         * @description An API key has no calling-user concept (unlike a Tenant Admin cookie session), so this is organization-scoped — sessions whose Session.organizationId matches the calling key's org (FR-105's "currently switched into this org") — not a "my own sessions" listing. Narrow to one member with `?userId=`.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page size, clamped to [1, 100]; invalid/absent falls back to the default. */
                    limit?: components["parameters"]["PageLimit"];
                    /** @description Opaque cursor from a previous page's `nextCursor` — omit for the first page. */
                    cursor?: components["parameters"]["PageCursor"];
                    /** @description Narrow the listing to one member's sessions. */
                    userId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cursor-paginated session list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            sessions: components["schemas"]["SessionInfo"][];
                            nextCursor: string | null;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a session (only if currently active within the calling organization) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Session id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the organization's in-app notification feed
         * @description Same organization-scoped-not-self reasoning as GET /sessions. Narrow to one member with `?userId=`. No read/unread state exists yet (§2.14's in-app channel is deliberately minimal — see TASKS.md).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page size, clamped to [1, 100]; invalid/absent falls back to the default. */
                    limit?: components["parameters"]["PageLimit"];
                    /** @description Opaque cursor from a previous page's `nextCursor` — omit for the first page. */
                    cursor?: components["parameters"]["PageCursor"];
                    /** @description Narrow the listing to one member's notifications. */
                    userId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cursor-paginated in-app notification list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            notifications: components["schemas"]["NotificationInfo"][];
                            nextCursor: string | null;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List which feature flags are currently enabled for the organization
         * @description FR-190-192's resolution precedence (user > organization > plan > global default) collapsed to the enabled-key set — no user context exists for an API key, so this resolves at the organization level. Read-only: no module registers a Feature yet (the catalog can be genuinely empty), and no override-management endpoint exists to pair a write with.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Enabled feature keys */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FeaturesResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the organization's own audit trail
         * @description The org-scoped counterpart to the Super Admin cross-org Report/Log viewer. Deliberately a trimmed field set — before/after diffs, ipAddress, userAgent, and metadata stay off the REST surface by default, same as the platform-wide viewer already exposes.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page size, clamped to [1, 100]; invalid/absent falls back to the default. */
                    limit?: components["parameters"]["PageLimit"];
                    /** @description Opaque cursor from a previous page's `nextCursor` — omit for the first page. */
                    cursor?: components["parameters"]["PageCursor"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cursor-paginated audit-log list, newest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            auditLogs: components["schemas"]["AuditLogEntry"][];
                            nextCursor: string | null;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        Organization: {
            id: string;
            name: string;
            slug: string;
            status: string;
            /** Format: date-time */
            createdAt: string;
        };
        Member: {
            membershipId: string;
            status: string;
            /** Format: date-time */
            createdAt: string;
            user: {
                id: string;
                /** Format: email */
                email: string;
                name: string | null;
                /** @description Read-only — whether this member has MFA enabled on their account. */
                mfaEnabled: boolean;
            };
        };
        Invite: {
            id: string;
            /** Format: email */
            email: string;
            roleId: string | null;
            invitedByUserId: string | null;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        SessionInfo: {
            id: string;
            userId: string;
            ipAddress: string | null;
            userAgent: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUsedAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        NotificationInfo: {
            id: string;
            userId: string;
            kind: string;
            subject: string;
            body: string;
            /** Format: date-time */
            createdAt: string;
        };
        Role: {
            id: string;
            name: string;
            slug: string;
            /** Format: date-time */
            createdAt: string;
        };
        RoleDetail: components["schemas"]["Role"] & {
            permissionKeys: string[];
        };
        Setting: {
            category: string;
            key: string;
            isSensitive: boolean;
            value: unknown;
        };
        ApiKey: {
            id: string;
            organizationId: string;
            name: string;
            keyPrefix: string;
            scopes: string[];
            /** Format: date-time */
            lastUsedAt: string | null;
            /** Format: date-time */
            expiresAt: string | null;
            /** Format: date-time */
            revokedAt: string | null;
            createdByUserId: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ApiKeyCreated: components["schemas"]["ApiKey"] & {
            /** @description Shown exactly once — never recoverable after this response. */
            rawKey: string;
        };
        Plan: {
            key: string;
            name: string;
            type: string;
            priceCents: number | null;
            currency: string;
            billingCycle: string | null;
            resources: {
                resourceTypeKey: string;
                limit: number | null;
            }[];
            features: {
                featureId: string;
                enabled: boolean;
            }[];
        };
        Subscription: {
            id: string;
            status: string;
            planKey: string | null;
            planName: string | null;
            /** Format: date-time */
            currentPeriodStart: string;
            /** Format: date-time */
            currentPeriodEnd: string;
            /** Format: date-time */
            trialEndsAt: string | null;
            /** Format: date-time */
            cancelAt: string | null;
        };
        InvoiceSummary: {
            id: string;
            number: string | null;
            status: string;
            currency: string;
            totalCents: number;
            /** Format: date-time */
            issuedAt: string | null;
            /** Format: date-time */
            paidAt: string | null;
            /** Format: date-time */
            dueAt: string | null;
        };
        InvoiceDetail: components["schemas"]["InvoiceSummary"] & {
            subtotalCents: number;
            taxCents: number;
            lineItems: {
                id: string;
                description: string;
                quantity: number;
                unitAmountCents: number;
                amountCents: number;
            }[];
        };
        OrganizationExport: {
            organization: components["schemas"]["Organization"];
            roles: {
                id: string;
                organizationId: string;
                name: string;
                slug: string;
                description?: string | null;
                /** Format: date-time */
                createdAt: string;
            }[];
            memberships: {
                id: string;
                organizationId: string;
                userId: string;
                status: string;
                /** Format: date-time */
                createdAt: string;
            }[];
            /** Format: date-time */
            exportedAt: string;
        };
        ResourceUsageEntry: {
            resourceTypeKey: string;
            unit: string;
            used: number;
            /** @description null = unlimited (no active subscription, or its plan doesn't allocate this resource type). */
            limit: number | null;
            overagePolicy: string;
        };
        FeaturesResponse: {
            /** @description Feature keys currently enabled for the organization. */
            enabled: string[];
        };
        AuditLogEntry: {
            id: string;
            actorUserId: string | null;
            module: string;
            action: string;
            resourceType: string | null;
            resourceId: string | null;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: {
        /** @description Validation error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Key is missing the required scope */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No resource with that id (including one belonging to another organization — FR-104) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request conflicts with existing state (e.g. already a member, or a pending invite already exists) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Page size, clamped to [1, 100]; invalid/absent falls back to the default. */
        PageLimit: number;
        /** @description Opaque cursor from a previous page's `nextCursor` — omit for the first page. */
        PageCursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
